### ISSUE TITLE
Can't enable the plugin...

### ISSUE THREAD

**Issue by WithAngeloDev** [limbonaut/limboai#113]
When I downloaded the build I tried to enable the plugin but I never found the option to enable it:
![image](https://github.com/limbonaut/limboai/assets/169811379/4e3f22d3-4f6a-40ad-a7fa-3c7e5f6e6034)
Thanks :D 👍

**Comment by limbonaut** [comment]
GDExtension plugins are not possible to enable/disable in that tab. You cannot enable or disable extension like you would with GDScript plugins. It's not a specific issue of LimboAI - it's true about most GDExtension plugins.

**Comment by WithAngeloDev** [comment]
> GDExtension plugins are not possible to enable/disable in that tab. You cannot enable or disable extension like you would with GDScript plugins. It's not a specific issue of LimboAI - it's true about most GDExtension plugins. It's auto-enabled when you put extension into your project (although you need to restart the editor).

Thanks ,but I tried downloading the extension from the AssetLib and restarted the project and still I can't use it for some reason...

**Comment by WithAngeloDev** [comment]
> > GDExtension plugins are not possible to enable/disable in that tab. You cannot enable or disable extension like you would with GDScript plugins. It's not a specific issue of LimboAI - it's true about most GDExtension plugins. It's auto-enabled when you put extension into your project (although you need to restart the editor).
> 
> Thanks ,but I tried downloading the extension from the AssetLib and restarted the project and still I can't use it for some reason...

found the issue
![image](https://github.com/limbonaut/limboai/assets/169811379/d6ba75f4-b862-43d9-8ffa-7c585fc65b70)
i need to use an older version ,Thanks :)

**Comment by limbonaut** [comment]
Yeah, there is an issue with the latest release, meaning that it works only starting with Godot 4.2.2. I'll fix it when tuxfamiliy.org comes back up.
