### ISSUE TITLE
Latest release v1.0.2 only works with Godot 4.2.2 and doesn't work with other 4.2.x versions (GDExtension)

### ISSUE THREAD

**Issue by limbonaut** [limbonaut/limboai#115]

**Comment by oncoremarco** [comment]
Seems like it's broken in 4.2.2 as well. I get a ton of errors on startup and it crashes Godot when I try to play the project.

**Comment by limbonaut** [comment]
@oncoremarco 
Could you provide a console log?

**Comment by D0radus** [comment]
I am encountering the same issue on 4.2.2. In The showcase.gd file errors with 
`Line 14:Could not find type "BehaviorTreeView" in the current scope.`
`Line 27:Could not find type "BTPlayer" in the current scope.`
`Line 45:Could not find type "BTTask" in the current scope.`
`Line 46:Could not find type "BehaviorTreeData" in the current scope.`
`Line 46:Identifier "BehaviorTreeData" not declared in the current scope.`

**Comment by limbonaut** [comment]
> I am encountering the same issue on 4.2.2. In The showcase.gd file errors with `Line 14:Could not find type "BehaviorTreeView" in the current scope.` `Line 27:Could not find type "BTPlayer" in the current scope.` `Line 45:Could not find type "BTTask" in the current scope.` `Line 46:Could not find type "BehaviorTreeData" in the current scope.` `Line 46:Identifier "BehaviorTreeData" not declared in the current scope.`

Those errors mean that extension is not loaded for some reason. One way to diagnose it is to run godot using console and check errors there. Did you install extension from asset library? FYI, just downloading the demo project is not enough.

**Comment by ClayZH** [comment]
> > I am encountering the same issue on 4.2.2. In The showcase.gd file errors with `Line 14:Could not find type "BehaviorTreeView" in the current scope.` `Line 27:Could not find type "BTPlayer" in the current scope.` `Line 45:Could not find type "BTTask" in the current scope.` `Line 46:Could not find type "BehaviorTreeData" in the current scope.` `Line 46:Identifier "BehaviorTreeData" not declared in the current scope.`
> 
> Those errors mean that extension is not loaded for some reason. One way to diagnose it is to run godot using console and check errors there. Did you install extension from asset library? FYI, just downloading the demo project is not enough.

#83 According to your step in this issue, install the plugin from asset library. Same errors still persist

**Comment by limbonaut** [comment]
I've uploaded a build of the v1.0.2 release that should work with any Godot 4.2.x version: https://github.com/limbonaut/limboai/releases/download/v1.0.2/limboai+v1.0.2.gdextension-4.2.zip
AssetLib pending.

**Comment by limbonaut** [comment]
Closing this issue, since the updated builds in the v1.0.2 release should work now with all 4.2.x patch versions. If it doesn't work for you, ping me.

**Comment by geeemok** [comment]
this happens again in 4.4-dev3。this error will always show up at the first boot, and will dispear after reboot
`Parser Error: Could not find type "LimboHSM" in the current scope.`

**Comment by limbonaut** [comment]
@geeemok 
These kinds of errors are "normal" for the first load, but they should not appear on the subsequent project launch. But if it happens again on next launch, you can try starting Godot from a console - sometimes it gives a useful error message you wouldn't see in Output pane.
