### ISSUE TITLE
Folding/unfolding selected composite task is not working

### ISSUE THREAD

**Issue by andmish** [limbonaut/limboai#134]
Tested latest build **v1.1-rc [2d1c5fa]**
Arrow keys are not working too, in **1.0.2** you could fold/unfold pressing left/right

![fold_click](https://github.com/limbonaut/limboai/assets/37307893/7c367281-36fe-4f36-9ba8-135153e937d0)

**Comment by limbonaut** [comment]
Interestingly, it works just fine until you select a task in front of the folding icon.
