### ISSUE TITLE
Missing methods on Blackboard object

### ISSUE THREAD

**Issue by razage** [limbonaut/limboai#137]
Version: Godot 4.2.2-Mono

I apologize if I'm misunderstanding the API.

I have a `LimboHSM` I'm using for turn management in a turn-based RPG.  The `LimboHSM` has a `BlackboardPlan` and I call `blackboard.top()` to reference that from the `LimboState`s themselves. I consulted the docs and saw the `get_vars_as_dict` and `populate_from_dict` methods and thought those would be more convenient than calling `set_var` and `get_var` dozens of times. But I get an error saying `Invalid call. Nonexistent function 'populate_from_dict' in base 'Blackboard'`.

Am I misunderstanding, or is this a bug?

**Comment by limbonaut** [comment]
Those methods are available in latest builds, not v1.0.2. You can use the latest pre-release version: https://github.com/limbonaut/limboai/releases

**Comment by razage** [comment]
Fair enough. I guess I didn't pay enough attention on the documentation haha.
