### ISSUE TITLE
How to use GDExtension build with C#?

### ISSUE THREAD

**Issue by leonardoraele** [limbonaut/limboai#138]
In the [`Using LimboAI with C#` page in the docs](https://limboai.readthedocs.io/en/latest/getting-started/c-sharp.html#using-limboai-with-c), the first step is to look for the `GodotSharp` folder, but the GDExtension build doesn't have this folder.

How to proceed? 🤔 Can I just use the `GodotSharp` folder from another build?

**Comment by limbonaut** [comment]
AFAIK, there is no official support for GDExtension in C# land. Dotnet side just doesn't see GDExtension classes. There maybe some workarounds, like a GDScript proxy object / wrapper, but performance will likely suffer. Would it matter, I don't know. In any case, I don't have a how-to to follow. Maybe someone else had success with integrating GDExtension into C# land in the past, and will share it here in this thread.

I also recently came upon this project: https://github.com/Delsin-Yu/CSharp-Wrapper-Generator-for-GDExtension
But I don't know if it works with LimboAI.

**Comment by leonardoraele** [comment]
That's unfortunate. Thanks for the response.

**Comment by ALapidis** [comment]
https://github.com/DmitriySalnikov/godot_debug_draw_3d
Is a GDExtension which fully supports GDScript or C#. Perhaps he can offer some insight into LimboAI's compatibility?

**Comment by limbonaut** [comment]
I'll close this as not planned - can't afford time to support it.

**Comment by limbonaut** [comment]
You can still use custom engine build with the corresponding GodotSharp glue as a local nuget source, as explained in the docs.

**Comment by StepanMynarik** [comment]
@limbonaut 
Custom engine build is perfectly fine solution, until you need other addon which also required custom engine build. Then you have to merge the custom changes from both and things get pretty complicated.

Also you have to wait for every minor engine update, like `4.6.2` for example.

Have you seen this https://github.com/gilzoide/godot-csharp-gdextension-bindgen ? I think it could help alleviate the manual labor.

No matter how you decide in this matter - I love you work and appreciate it very much. Thank you ❤️ 
It is a pleasure to work with both LimboAI and Limbo Console! Even in C#!
