### ISSUE TITLE
LimboAI 1.0.2: Blackboard.link_var() and bind_var_to_property() do not expose 'create' param for GDScript

### ISSUE THREAD

**Issue by smedelyan** [limbonaut/limboai#141]
[The doc](https://limboai.readthedocs.io/en/latest/classes/class_blackboard.html#class-blackboard-method-link-var) says:

> void link_var ( StringName var_name, [Blackboard](https://limboai.readthedocs.io/en/latest/classes/class_blackboard.html#class-blackboard) target_blackboard, StringName target_var, bool create=false )
> ...
>  If `create` is `true`, the variable will be created if it doesn’t exist.

However, in GDScript `create` is not available:

![image](https://github.com/limbonaut/limboai/assets/47334605/93d129ce-6760-40fa-95c1-6833d8d063c2)

Same for `bind_var_to_property()`

**LimboAI version:** `1.0.2`

---

I can see that there is a [var binding](https://github.com/limbonaut/limboai/blob/fc5307813013f4c7d8241a0ae140a0cd3b0a5b24/blackboard/blackboard.cpp#L144), so maybe it just didn't end up in the latest (`1.0.2`) release?

**Comment by smedelyan** [comment]
Ok, I found this: https://github.com/limbonaut/limboai/releases/tag/v1.1-rc

It seems it's already scheduled for the 1.1 release so feel free to close this issue

**Comment by limbonaut** [comment]
It's not a bug - you are using `latest` documentation with `v1.0.2`. There is a separate docs branch for 1.0 stable releases: https://limboai.readthedocs.io/en/v1.0/

You can switch doc branches in the bottom-left panel:
![image](https://github.com/limbonaut/limboai/assets/2766569/b75878f0-0803-4b11-99ce-29334906c2f8)
