### ISSUE TITLE
Icon color conversion

### ISSUE THREAD

**Issue by ckaiser** [limbonaut/limboai#144]
By default the current workflow for the GDExtension export is not setting the `convert_colors_with_editor_theme` flag to true on the svg icons, which causes them to not have their colors replaced for light themes, resulting in some inconsistencies with the rest of the editor:
![image](https://github.com/limbonaut/limboai/assets/138269/f5f46c0d-0b94-46fa-a0a4-6f1563575c7b)

Haven't tested it in the editor build, but I assume that issue is bypassed there from just using the editor-side icon loader.

**Comment by limbonaut** [comment]
Thanks!
