### ISSUE TITLE
BTPlayer::restart() crashes if behavior tree is missing

### ISSUE THREAD

**Issue by smedelyan** [limbonaut/limboai#168]
### Godot version

4.2.2

### LimboAI version

v1.1.0

### LimboAI variant

GDExtension / AssetLib

### Issue description

When `BTPlayer::restart()` is called while there is no behavior tree, game crashes. The offending line seems to be this one:
![image](https://github.com/user-attachments/assets/1216b6fb-949b-43e2-8918-8494860d4c66)
Quick fix would be:
![image](https://github.com/user-attachments/assets/4d9fe480-4276-425f-92df-108c8dad3b3a)

### How to reproduce

1. Create an empty (no behavior tree) `BTPlayer` node
2. Invoke its `restart()` from code

**Comment by limbonaut** [comment]
Thanks for reporting
