### ISSUE TITLE
Error signal `changed` is already connected if instance of scene is open in editor

### ISSUE THREAD

**Issue by ydeltastar** [limbonaut/limboai#179]
### Godot version

v4.3.rc

### LimboAI version

v1.2-dev [0918521]

### LimboAI variant

Module (custom editor or template build)

### Issue description

Many task types such as `BTCallMethod`, `BTSetVar`, `BTCheckAgentProperty`, and `BTPlayAnimation`, give a signal already connected error when I load the project in the editor.

This only happens when I have a scene with a behavior tree, it is instanced in a parent scene, and both child and parent scenes are open when the project loads.

>   Signal 'changed' is already connected to given callable 'BTCallMethod::emit_changed' in that object.
>   Signal 'changed' is already connected to given callable 'BTSetVar::emit_changed' in that object.
>   Signal 'changed' is already connected to given callable 'BTCheckAgentProperty::emit_changed' in that object.

### How to reproduce

- Create a parent scene.
- Create a child scene with a `BTPlayer` and a `BTCallMethod` task and instantiate it in the parent scene.
- Make sure both scenes are open in the editor and `Project > Reload Current Scene`
- It will raise signal errors

MRP: [limbo-signal-error.zip](https://github.com/user-attachments/files/16457336/limbo-signal-error.zip)
Open "main.tscn" and "cube.tscn" and reload the project.

**Comment by limbonaut** [comment]
I couldn't reproduce it even with the help of MRP. There must be some other piece missing here. But I can trace it using your error log. Let's see if I can fix it this way.

**Comment by limbonaut** [comment]
@ydeltastar 
Can you confirm if #180 resolves this issue? 
You can grab a build [here](https://github.com/limbonaut/limboai/actions/runs/10212236154).

**Comment by ydeltastar** [comment]
Strange, I can reproduce it in any project. It looks like the order matter, "main" should be the first in the scene tabs and "cube" the last. It doesn't give an error when I invert the order.

I tested the artifact and it fixed the issue. Thanks!

**Comment by limbonaut** [comment]
Merging then. Thanks for reporting.
