### ISSUE TITLE
LimboHSM.change_active_state(). Invalid call. Nonexistent function 'change_active_state" in base 'LimboHSM'

### ISSUE THREAD

**Issue by dragoonreign** [limbonaut/limboai#187]
### Godot version

v4.2 godot

### LimboAI version

v1.1.0

### LimboAI variant

GDExtension / AssetLib

### Issue description

Downloaded limbo ai from asset lib

When calling the method LimboHSM.change_active_state(), it displays an error below.

"Invalid call. Nonexistent function 'change_active_state" in base 'LimboHSM'"

### How to reproduce

Code below
`
    @onready var super_sm: LimboHSM = $SuperHSM
    @onready var grounded_sm: LimboHSM = $SuperHSM/grounded
    super_sm.change_active_state(grounded_sm.initial_state)

`

**Comment by limbonaut** [comment]
This method is not available in v1.1.0. You're probably reading `latest` documentation. You can switch documentation version in the bottom-left panel.
![image](https://github.com/user-attachments/assets/7f262dab-d04a-4cd1-b669-2231b3047c64)
