### ISSUE TITLE
GDextension "overrides a method from native class"

### ISSUE THREAD

**Issue by pyrohair** [limbonaut/limboai#19]
When using the GDextension (downloaded from the Godot Asset Library), creating a new [custom task based on the template](https://limboai.readthedocs.io/en/latest/getting-started/custom-tasks.html) throws a bunch of "overrides a method from native class" errors for each method:

```Line 13:The method "_generate_name()" overrides a method from native class "BTTask". This won't be called by the engine and may not work as expected. (Warning treated as error.)
Line 18:The method "_setup()" overrides a method from native class "BTTask". This won't be called by the engine and may not work as expected. (Warning treated as error.)
Line 23:The method "_enter()" overrides a method from native class "BTTask". This won't be called by the engine and may not work as expected. (Warning treated as error.)
Line 28:The method "_exit()" overrides a method from native class "BTTask". This won't be called by the engine and may not work as expected. (Warning treated as error.)
Line 33:The method "_tick()" overrides a method from native class "BTTask". This won't be called by the engine and may not work as expected. (Warning treated as error.)
Line 38:The method "_get_configuration_warnings()" overrides a method from native class "BTTask". This won't be called by the engine and may not work as expected. (Warning treated as error.)```

**Comment by limbonaut** [comment]
It's fixed already in the `master`, and should be out in the `dev2` release next week.
You can use this build in a mean time (scroll down until you see **Artifacts** section): https://github.com/limbonaut/limboai/actions/runs/7584508210 (scroll down).

**Comment by pyrohair** [comment]
> It's fixed already in the `master`, and should be out in the `dev2` release next week. You can use this build in the meantime (scroll down until you see **Artifacts** section): https://github.com/limbonaut/limboai/actions/runs/7584508210

Can confirm the linked build solves this bug. Thanks for the pointer!
