### ISSUE TITLE
A way to filter tasks in the tree view

### ISSUE THREAD

**Issue by ydeltastar** [limbonaut/limboai#192]
### Problem statement

While prototyping and editing scripts, I usually need to find all the instances of a task and fix export values, remove them, or just find where it is used.
There is no filter for the tree view so I have to pinpoint tasks by eye, which becomes more difficult as the tree grows larger.

### Proposed solution

A filter feature for the behavior tree view similar to the filter in the scene tree.
It can take a name string and optionally a type. Nodes that don't match the filter are hidden but the parent structure is visible.

Usage example, based on the scene tree filter behavior:
* Filter `can_melee t:BTCheckVar` will show all `BTCheckVar` tasks containing "can_melee" in their generated names.
* Matches don't need to be precise so `can_melee t:checkVar` and `_melee t:check` will have the same result
* Support for multiple matches. Filter `can_melee t:BTCheckVar NavigateToPos` will show both `BTCheckVar` containing "can_melee" and a custom task named `NavigateToPos`

The filter could be fixed on the top like the scene's node tree but since the behavior editor is a main dock, it could work like the script editor's Find feature. It is placed at the bottom, can be accessed with `Ctrl+F`, and can be hidden.

### Alternatives

N/A

**Comment by monxa** [comment]
Design proposal: Two options 
1. Filter tree: show only trees with matching subtree names/base names. 
2. Highlight tree: highlight matches or show right-side indicators (with match count for multiple hits).

**Comment by ydeltastar** [comment]
Filter or highlight option could be implemented as the "Show All" toggle like in the node selector.

![image](https://github.com/user-attachments/assets/e9c3b69c-f2b1-4ad3-bc5b-1ae3799d7880)

**Comment by monxa** [comment]
Yes, consistency is nice, especially naming consistency. 
I initially imagined filtering to allow using the tree as-is while filtered. For example, you could mask for a parent and then edit its subtree without being distracted by other parts.

On the other hand, if we went all-in with the Godot-internal node selector design, the filter option would be usable in exactly this way:
- search
- select element
- exit filtering

This is an improvement, and I am all for it. It's your proposal after all. I'm all ears which direction this should go.

**Comment by monxa** [comment]
Don't want to unnecessarily bump this but Tuesday I got some time. I will try to implement this. I will go with @ydeltastars suggestion if nothing else is suggested. @ydeltastar If you are already working on this, please let me know!

**Comment by ydeltastar** [comment]
> I initially imagined filtering to allow using the tree as-is while filtered. For example, you could mask for a parent and then edit its subtree without being distracted by other parts.

That's how I imagined it too. Similar to the scene tree filter but with an option to hide/show filtered-out tasks which the scene tree doesn't have.

Sounds great! I haven't worked on this yet.

**Comment by limbonaut** [comment]
Such functionality would be quite useful. :+1:  UI needs some consideration - that main toolbar is so packed. Make sure to also take the new layout into consideration.

**Comment by monxa** [comment]
![image](https://github.com/user-attachments/assets/e2fd9cc3-deb2-49cc-9d6e-8f221dbc37a1)

**Comment by limbonaut** [comment]
Yeah, that can work

**Comment by monxa** [comment]
Update: Custom class added for TaskTree simplicity. Exploring selection for navigation and highlighting. Filtering planned for Sunday, may take longer. Open to any feedback.
