### ISSUE TITLE
SetAgentProperty generated name with operation symbol

### ISSUE THREAD

**Issue by m-radzikowski** [limbonaut/limboai#209]
### Problem statement

Right now, no matter the selected Operation, generated name for SetAgentProperty is always `Set agent.PROPERTY = VALUE`:

https://github.com/limbonaut/limboai/blob/1cb85807dd3b92be837d7884d3fecbe84a5e8aba/bt/tasks/scene/bt_set_agent_property.cpp#L44-L51

However, the operation can be not "set", but addition, subtraction, etc. It makes a somewhat confusing in the UI if you see that you assign a value while in fact you are, for example, adding to the value.

### Proposed solution

Implement setting the operator symbol based on the operation, just like in CheckAgentProperty:

https://github.com/limbonaut/limboai/blob/1cb85807dd3b92be837d7884d3fecbe84a5e8aba/bt/tasks/scene/bt_check_agent_property.cpp#L44-L52

Symbols are quite obvious and can be the same as in GDScript (and many other langs) assignments ([see end of this table](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#operators)):

| Operation             | Symbol |
|-----------------------|--------|
| None (default, "set") | =      |
| Addition              | +=     |
| Subtraction           | -=     |
| Multiplication        | *=     |
| Division              | /=     |
| Modulo                | %=     |
| Power                 | **     |
| Bitwise Shift Left    | <<=    |
| Bitwise Shift Right   | >>=    |
| Bitwise AND           | &=     |
| Bitwise OR            | \|=    |
| Bitwise XOR           | ^=     |

I can implement it and open a PR. I probably won't be able to test it locally, but I see there are github actions workflows so I can test that it builds 😉

### Alternatives

None?

**Comment by limbonaut** [comment]
It's a bug. I propertly implemented it in https://github.com/limbonaut/limboai/blob/master/bt/tasks/blackboard/bt_set_var.cpp, but it looks like I forgot to change it in this one.

**Comment by limbonaut** [comment]
Thanks for reporting!
