### ISSUE TITLE
Blackboard plan crashes

### ISSUE THREAD

**Issue by witchpiggie** [limbonaut/limboai#220]
### Godot version

v4.3.stable.official [77dcf97d8]

### LimboAI version

v1.2.2

### LimboAI variant

GDExtension / AssetLib

### Issue description

Godot editor silently crashes when using Blackboard plans.
In the editor, I will make a blackboard plan, make a few entries. Set some values on those.
Then I hop over to vscode (using godot-tools) and start working. It doesn't usually take long,
but I will be working and the editor will just quit.
I can confirm it *is* the blackboard plans as far as I can tell. I don't get crashes when I don't use them.
As soon as I try again, it will crash.
I'm not sure if it's an issue with using an external editor or not.

### How to reproduce

- Make a game.
- Make a CharacterBody2D
- Add LimboHSM node with a couple LimboState nodes
- Add a blackboard plan to the LimboHSM node .
- Add some variables into the board and set their values.
- Go edit code.
- ... At some point Godot just closes with no error.

**Comment by limbonaut** [comment]
I couldn't reproduce it following those steps. It would be much easier to find the problem if we had a backtrace. When Godot crashes, it prints a backtrace to the console, however it's not very usable without debug symbols. To be able to read it, you'd need to run godot engine from a console and use a debug build of LimboAI plugin (with the debug symbols included). Can you do that? I can provide a debug build: https://github.com/limbonaut/limboai/actions/runs/10971096353
Just replace your `addons/limboai` folder with the one from the archive.

**Comment by witchpiggie** [comment]
I'll see what I can do.

**Comment by Ragueel** [comment]
having the same issue with 4.3, It randomly crashes when opening blackboard plan resource, also noticed that sometimes Mappings does not appear not sure why
