### ISSUE TITLE
Remember last session of the `BehaviorTree` editor

### ISSUE THREAD

**Issue by ydeltastar** [limbonaut/limboai#221]
### Problem statement

Editor plugins can remember what was open when the editor closed and load it at startup. This feature isn't implemented for the behavior tree editor.

### Proposed solution

I implemented it using the `limbo_ai.cfg` and regular node notification like the current codebase but I was wondering why the addon uses a separate configuration file instead of `EditorPlugin::set/get_window_layout`.

If there is no specific reason, I'd like to move it to these callbacks and the default `editor_layout.cfg`. `EditorPlugin::set_window_layout` in particular is required to get the same behavior as the other editor plugins. It happens after the screen is set up while regular notifications like `NOTIFICATION_ENTER_TREE/READY` happen too early so I had to use a deferred call hack to load the trees, which works but still happens too early.

### Alternatives

N/A

**Comment by limbonaut** [comment]
That's just some old code. I don't mind if we change it to a more canonical way.
