### ISSUE TITLE
`BTParallel` parameters `num_successes_required` and `num_failures_required` have swapped documentation

### ISSUE THREAD

**Issue by hohfchns** [limbonaut/limboai#236]
### Godot version

4.3

### LimboAI version

1.2.2

### LimboAI variant

GDExtension / AssetLib

### Issue description

In the `BTParallel` class:

The documentation for `num_failures_required` says:
```
if the specified number of child tasks return SUCCESS, BTParallel will also return SUCCESS.
```

The documentation for `num_successes_required` says:
```
if the specified number of child tasks return FAILURE, BTParallel will also return FAILURE.
```

This is opposite both in practice and with the variable names

### How to reproduce

- Download the plugin
- Go to the documentation for the `BTParallel` class

**Comment by limbonaut** [comment]
This is already fixed in the master.

**Comment by hohfchns** [comment]
Great, thank you!
