### ISSUE TITLE
Changing BT Player Behaviour Tree in runtime causing Crash

### ISSUE THREAD

**Issue by superhighlevel** [limbonaut/limboai#254]
### Godot version

v4.3.stable.official [77dcf97d8]

### LimboAI version

v1.2.2 [d3d3295]

### LimboAI variant

GDExtension / AssetLib

### Issue description

Hello, thank you for the awesome AI framework.
The game crashes when I try to change the Behaviour Tree of BT Player through an action as a trigger.

### How to reproduce

1. Install LimboAI from AssetLib
2. Create 2 Action nodes with separate classes with an export behavior tree, controlled by an action manager, in Agent.
3. When Action 1's behavior tree has done its job, use a BTTask as a trigger to change the behavior tree through Agent.
[behaviourtreebug.zip](https://github.com/user-attachments/files/17995826/behaviourtreebug.zip)

**Comment by limbonaut** [comment]
Thanks for the MRP. Fixed it in #255.
