### ISSUE TITLE
Make user task directories in project settings dynamicly sized.

### ISSUE THREAD

**Issue by Pheubel** [limbonaut/limboai#256]
### Problem statement

I want to make a bullethell plugin that builds upon limbo AI's behavior trees in order to get more specialized behavior. For this i want to make my own tasks and be able to register them so i can use them in projects that make use of the plugin. However, since there are 3 slots for user task directories, it limits how reliable my plugin could register itself without overwriting an existing entry.

### Proposed solution

Instead of having a set amount of task directories in the project settings, there instead could be a single setting called `User Task Directories` of type `PackedStringArray`, with the first item set to `res://ai/tasks` by default.

From there i could then register the directory inside my own plugin, or alternatively, a (editor only) helper function could be created and exposed to automatically handle registering and unregistering the directory when the plugin gets enabled/disabled by the end developer.

### Alternatives

N/A

**Comment by limbonaut** [comment]
I support this, since the way it's implemented is simply historical.
