### ISSUE TITLE
Suggestion on documentation structure

### ISSUE THREAD

**Issue by namelessvoid** [limbonaut/limboai#259]
### Problem statement

As a newcomer to LimboAI, the documentation hosted at https://limboai.readthedocs.io/en/stable/ felt a bit hard to understand. 

For example, after navigating away from the index page, it is hard to find the installation instructions. They are not linked in the navigation menu and one has to remember that it's possible to click the logo / the little home icon bread crumb and that the info might be there. Especially on mobile that took me some time to find the instructions.

The pages are a bit mixed. Some GDExtension info is on the index page, some on a sub page. Same for C# support. Also Behavior Tree and HSM pages are a bit mixed.

### Proposed solution

Make the page structure cleaner. A proposal could be:

- Getting Started
   - Installation
   - Using LimboAI with C#
 - Behavior Trees
    - Introduction to Behavior Trees
    - Creating a behavior tree
    - Custom Tasks
    - ...
- Hierarchical State Machines
   - Introduction to HSM
   - Creating a HSM
   - Using Behavior Trees in state machines
   - ...
 
If you like this idea, I can create a PR :)

### Alternatives

No alternatives to propose.

**Comment by limbonaut** [comment]
I do like the idea. We may lack some content for such a structure, though, but if you're willing to work on it, I'd always welcome such effort 🙂

**Comment by namelessvoid** [comment]
@limbonaut So the PR was merged, but I cannot see the updated docs yet. Did anything go wrong? Is there a way for me to check e.g. the deployment?

**Comment by limbonaut** [comment]
Unfortunately, as documentation updates are fully automated, we'd have to wait until next version. I think I'll simply revert the README changes.

**Comment by namelessvoid** [comment]
I was not familiar with the release strategy of read the docs. After reading about that, I agree, reverting the readme changes sounds most reasonable. Thank you for rolling back!

**Comment by limbonaut** [comment]
No worries, I also forgot about the links, thanks for bringing it up.

**Comment by namelessvoid** [comment]
Yup, it works again :+1:

As far as I'm concerned, this suggestion is resolved. Feel free to close the issue or keep it open as a reminder to re-revert for the next release -- it's up to you! :)

And thanks for being open and accepting my suggestions! Highly appreciated :)
