### ISSUE TITLE
BehaviorTreeData invisible to the parser or not included at all

### ISSUE THREAD

**Issue by hsoler** [limbonaut/limboai#38]
Hey, I am using Godot 4.2 stable.

I just git cloned the LimboAI repo from github, launched Godot and imported a new project, from the "project.godot" file included in the "demo" directory in cloned LimboAI repo. I then installed the LimboAI plugin from the AssetLib into that project, in the default folder "addons", and launched the main scene with F5.

Weirdly, the program crashed, and in the terminal which I used to monitor its execution, it was saying that Godot's parser could not find the "BehaviorTreeData" of which the variable "bt_data" being declared in line 30 in the script attached to the main scene's root node "AgentShowcase" was therein being typed. It seemed to me, though I certainly know worse, that this must be a BehaviorTreeData-specific issue, since the variable declarations above in the script succeeded in being typed from other LimboAI's classes, such as BehaviorTreeView and BTPlayer.

Additionally, I started a new project in Godot, installed the LimboAI plugin from AssetLib, created a scene with a CharacterBody2D root node and attached a script to it. Therein, I declared in a line "class MyClass extends BehaviorTreeData: pass", to see the parser once again not see BehaviorTreeData in the current scope and throw a parser error message. I've had experiences with Godot native parser bugs in the past, so I'm not entirely confident this is a LimboAI issue, if an issue at all or just a misunderstanding of my part about the proper use of LimboAI.

For now, I'll try to compile the engine with the LimboAI module included, and see if this behavior persists. If this is not a bug but rather an expected functionality, I'd appreciate a warning.

Anyway, thanks in advance, for any support eventually directed towards the resolution of this problem, and for the awesome work on developing and releasing this library so far.

**Comment by hsoler** [comment]
By the way, I forgot to mention: I am using Linux x86_64, GCC 13.1

**Comment by cmontesano** [comment]
If you are running a pre-compiled release please check that you are using the demo from its release tag (e.g. [v0.5](https://github.com/limbonaut/limboai/releases/tag/v0.5)) and not a more recent version.

**Comment by limbonaut** [comment]
The demo project in the master branch is very new and requires one of the latest builds, no currently released version will work! @hsoler, you can use this build in a meantime: https://github.com/limbonaut/limboai/actions/runs/7906806243

**Comment by hsoler** [comment]
Thanks, folks. I've gone with Limbonaut's suggestion for running the demo with the latest test build available. It worked all right to me this time.
