### ISSUE TITLE
Allowing resume behavior tree by set tree instance manually.

### ISSUE THREAD

**Issue by ODtian** [limbonaut/limboai#73]
Currently, we can obtain the running instance of a behavior tree by invoking `BTPlayer.get_tree_instance()`. However, there are times when a user may wish to temporarily exit the current behavior tree to execute a different one and return to it later. This is a common scenario when utilizing smart objects, as it allows for the transfer of actor control between different behavior trees."

Possible implement: When you are prepared to exit, encapsulate the BT context within an object and return it to the user. This object can then be passed to the resume method to continue the BT.

**Comment by limbonaut** [comment]
**Potential Workaround**: Add multiple `BTPlayer` nodes to the scene tree, and activate/deactivate them on demand (see `BTPlayer.active`).

**Comment by limbonaut** [comment]
Closing as it was implemented some time ago
