### ISSUE TITLE
Default BBInt shows as 0 but is actually null

### ISSUE THREAD

**Issue by onze** [limbonaut/limboai#76]
I'm attaching a minimal project to reproduce, but long story short the issue is that for a BBInt left to its default value shows as `0` in the editor panel:
![image](https://github.com/limbonaut/limboai/assets/297607/f03f4d26-e333-4795-973e-8270f837d19a)
but actually returns a `null` value.

Now I tried incrementing & then decrementing the value, in order to actually _set_ it to 0, and in that case it works as expected. All summed up here:
```
@tool
extends BTAction

@export var my_bbint_default: BBInt
@export var my_bbint_0: BBInt
@export var my_bbint_1: BBInt

func _enter() -> void:
	assert(my_bbint_default.value_source == BBParam.ValueSource.SAVED_VALUE)
	print(my_bbint_default.saved_value) # null, would expect 0
	print(my_bbint_default.get_value(agent, blackboard)) # null, would expect 0
	
	assert(my_bbint_0.value_source == BBParam.ValueSource.SAVED_VALUE)
	print(my_bbint_0.saved_value) # 0 as expected
	print(my_bbint_0.get_value(agent, blackboard)) # 0 as expected
	
	assert(my_bbint_1.value_source == BBParam.ValueSource.SAVED_VALUE)
	print(my_bbint_1.saved_value) # 1 as expected
	print(my_bbint_1.get_value(agent, blackboard)) # 1 as expected
	
	print('all good')

```

So this may not be an issue... once we know it :sweat_smile: 

[limboai_bbparam_issue.tar.gz](https://github.com/limbonaut/limboai/files/14670609/limboai_bbparam_issue.tar.gz)

**Comment by limbonaut** [comment]
Seems like it only affects GDExtension version.
