### ISSUE TITLE
dispatch() causes freeze to nested HSM

### ISSUE THREAD

**Issue by niceWizzard** [limbonaut/limboai#97]
## Issue
![image](https://github.com/limbonaut/limboai/assets/62689803/6b83ebfb-0e53-4df3-8ed9-56295a582721)
This is the structure of my states

The IdleState from StandingHSM runs, but when I call dispatch in the IdleState, the game just freezes. 

Here is how I initialize the root HSM

```python
extends CharacterBody2D

@export var speed := 200.0
@export var hsm: LimboHSM
@export var standing: LimboState
@export var crouching: LimboState

func _ready() -> void:
	initialize_state()

func initialize_state():
	hsm.add_transition(standing, crouching, "crouch_start")
	hsm.add_transition(crouching, standing, "crouch_end")
	hsm.initialize(self)
	hsm.set_active(true)
```

Standing HSM
```python
extends LimboHSM

@export var idle: LimboState
@export var walking: LimboState
@export var sprinting: LimboState

func _setup():
	initialize_state()

func initialize_state():
	add_transition(idle, walking, "walk_start")
	add_transition(walking, idle, "walk_end")
	add_transition(ANYSTATE, sprinting, "sprint_start")
	add_transition(sprinting, idle, "sprint_end")
```

```python
## Code from standing/idle_state.gd
func _update(delta: float) -> void:
	var input_dir := Input.get_vector("move_left", "move_right", "move_up", "move_down")
	if input_dir.length() > 0:
		get_root().dispatch("walk_start") ## Causes freeze
		return
	agent.velocity = Vector2.ZERO
	agent.move_and_slide()
```
- I have tried dispatch(), get_root().dispatch(), it freezes the game anyways, it doesn't help the fact that there is no error log in the editor. 
- I have also tried running the project in v4.2.1, it still is the same

### System Info
- Godot 4.2.2
- Windows 11

## Reproduction Steps
1. Clone: <https://github.com/niceWizzard/LimboAI_dispatch_freeze>
2. Run the game 
3. If you were to press WASD (movement input), game freezes

**Comment by limbonaut** [comment]
I was just about to release 1.0.2 that should fix this. Check https://github.com/limbonaut/limboai/pull/93
