### ISSUE TITLE
How to use the tutorial scenes?

### ISSUE THREAD

**Issue by TranquilMarmot** [limbonaut/limboai#99]
I notice after installing the addon that there's a `demo/agents/tutorial` folder that contains a lot of tutorial scenes.

How are these supposed to be used? Opening them up and running the scenes, nothing seems to happen.

**Comment by TranquilMarmot** [comment]
Okay, I think I see- if you run the `game.tscn` scene, you can click "Switch to showcase" and then "Begin tutorial".

Is there a way to begin the tutorial directly?

**Comment by limbonaut** [comment]
`demo/agents/tutorial/` contain the agents for the tutorial itself. The scene that uses those is `demo/scenes/showcase.tscn`.
